//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use super::sea_orm_active_enums::GenderType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "customer")]
pub struct Model {
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub company: Option<String>,
    pub street: String,
    pub city: String,
    pub state: String,
    pub zip: i16,
    pub phone: String,
    pub birth_date: Option<Date>,
    pub sex: GenderType,
    pub date_entered: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
