//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender_type")]
pub enum GenderType {
    #[sea_orm(string_value = "F")]
    F,
    #[sea_orm(string_value = "M")]
    M,
}
